# Generated by Django 5.1 on 2024-11-30 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_treatpledge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatpledge',
            old_name='treats_sacrificed',
            new_name='treats_pledged',
        ),
    ]
