# Generated by Django 5.1 on 2024-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://scontent.fper7-1.fna.fbcdn.net/v/t39.30808-6/369978875_621935253411512_4526444535835746883_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=IcmxA-5_jwUQ7kNvgEpOrIG&_nc_zt=23&_nc_ht=scontent.fper7-1.fna&_nc_gid=AynHdYIiRX3Bq5mt4BSJTaD&oh=00_AYCXXrkgBRoJJiO6HM2TdIz3l7xwPQ4vPtwYNb3fl0CuKw&oe=6759D33C', max_length=1000, null=True),
        ),
    ]
