# Generated by Django 5.1 on 2024-12-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, default='https://github.com/domspenc/crowdfunding_backend/raw/main/resources/beanefactor_test_logo.jpg', max_length=1000, null=True),
        ),
    ]
