# Generated by Django 5.1 on 2024-12-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_treat_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', null=True, upload_to='project_images/'),
        ),
    ]
